---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    Bearer:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
paths:
  "/api/v1/users/sign_in":
    post:
      summary: Sign In
      tags:
      - Authentication
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Signed in successfully.
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: authentication token
                        example: eyJ1c2VyX2lkIjoiMDE5YTc3ZGMtOWYyOS00ODNjLThhZTAtMzBlNTU1MDVlODNiIiwiZXhwIjoxNjYzNzgwMDgzfQ
                      expires_at:
                        type: string
                        description: expiry date and time
                        example: 01-01-2022 17:08
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Missing Parameter
                    example: Email and password are required fields.
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Incorrect credentials
                    example: Could not authenticate. Please check your credentials and try again.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User email
                  example: test@test.com
                password:
                  type: string
                  description: User password
                  example: '12345678'
              required:
              - email
              - password
        description: Sign in with your user credentials to receive an authentication token. This Bearer token must be included in the authorization header for requests to all other endpoints.
  "/api/v1/listings/titles":
    post:
      summary: Listing Titles
      tags:
      - Listings
      security:
        - bearerAuth: []
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Successfully generated titles
                  data:
                    type: object
                    properties:
                      result:
                        type: array
                        example:
                          - 2 bedroom apartment with sea views and heated pool in Malaga
                          - Luxurious 2 Bedroom Apartment with Stunning Sea Views and Heated Pool
                          - Perfect for couples - sea views - heated swimming pool
                          - 2 bedroom apartment with sea views close to shops and restaurants
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Unauthtorized
                    example: Nil JSON web token
        '400':
          content:
            application/json:
              schema:
                type: array
                items: message
                example:
                  - message: Field(s) missing. Required fields are property_type, ideal_for, location, number_of_bedrooms, features
                  - message: property_type should be less than 70 characters
                  - message: location should be less than 70 characters
                  - message: ideal_for should be less than 70 characters
                  - message: feature should be less than 360 characters in total
                  - message: number_of_bedrooms should be between 0 and 100
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                output_language:
                  type: string
                  description: Output Language
                  example: EN
                text:
                  type: object
                  properties:
                    location:
                      type: string
                      description: Location
                      example: Malaga
                    property_type:
                      type: string
                      description: Property Type
                      example: apartment
                    number_of_bedrooms:
                      type: string
                      description: Number Of Bedrooms
                      example: 2
                    ideal_for:
                      type: string
                      description: Ideal For
                      example: couples or small families
                    features:
                      type: array
                      example:
                        - sea views
                        - heated swimming pool
                        - close to shops and restaurants
              required:
              - location
              - property_type
              - ideal_for
              - number_of_bedrooms
        description: Generate listing titles.
  "/api/v1/listings/descriptions":
    post:
      summary: Listing Descriptions
      tags:
      - Listings
      security:
        - bearerAuth: []
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Successfully generated descriptions
                  data:
                    properties:
                      result:
                        type: array
                        example:
                          - The perfect spot for a romantic getaway, this 2 bedroom apartment in Malaga offers couples stunning sea views from the large balcony and all the amenities they need for a comfortable stay, including a heated swimming pool. The open plan living space is perfect for socialising, and the apartment is close to shops and restaurants, making it easy to get around. What's more, it's just a short drive from the airport.
                          - This two bedroom apartment in Malaga is the perfect place for couples to enjoy a relaxing holiday. The apartment has a heated swimming pool, and a large balcony with sea views. The property is close to shops and restaurants, and a short drive to the airport.
                          - This two bedroom apartment in Malaga is ideal for couples and has sea views from the balcony. The apartment has an open plan living space and a heated swimming pool, perfect for lazy days. It's also close to shops and restaurants, and is just a short drive to the airport.
                          - This is an ideal apartment for couples looking for a romantic vacation in Malaga. The apartment enjoys stunning sea views, is beautifully furnished and is close to shops and restaurants. It also has a large balcony and a heated swimming pool.
                          - Enjoy a romantic break in Malaga from this two-bedroom apartment with sea views! The apartment has a large balcony and an open plan living space, with a heated swimming pool for you to enjoy together. It is ideal for couples and is just a short drive to the airport.
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Unauthtorized
                    example: Nil JSON web token
        '400':
          content:
            application/json:
              schema:
                type: array
                items: message
                example:
                  - message: Field(s) missing. Required fields are property_type, ideal_for, location, number_of_bedrooms, features
                  - message: property_type should be less than 70 characters
                  - message: location should be less than 70 characters
                  - message: ideal_for should be less than 70 characters
                  - message: feature should be less than 360 characters in total
                  - message: number_of_bedrooms should be between 0 and 100
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                output_language:
                  type: string
                  description: Output Language
                  example: EN
                text:
                  type: object
                  properties:
                    location:
                      type: string
                      description: Location
                      example: Malaga
                    property_type:
                      type: string
                      description: Property Type
                      example: apartment
                    number_of_bedrooms:
                      type: string
                      description: Number Of Bedrooms
                      example: 2
                    ideal_for:
                      type: string
                      description: Ideal For
                      example: couples
                    features:
                      type: array
                      example:
                        - sea views
                        - large balcony
                        - heated swimming pool
                        - open plan living space
                        - close to shops and restaurants
                        - short drive to the airport
              required:
              - location
              - property_type
              - ideal_for
              - number_of_bedrooms
        description: Generate listing descriptions.
  "/api/v1/area/search_locations":
    post:
      summary: Search Locations
      tags:
      - Area Descriptions
      security:
        - bearerAuth: []
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Successfully generated results
                  data:
                    type: object
                    properties:
                      search_location_id:
                        type: string
                        description: Search Location ID
                        example: 73b59600-e130-484b-a156-045a42215a52
                      search_results:
                        type: object
                        properties:
                          attractions:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: Trafalgar Square
                                categories:
                                  type: array
                                  items:
                                    type: string
                                    example: tourist_attraction
                                total_ratings:
                                  type: integer
                                  example: 2248
                                place_id:
                                  type: string
                                  example: 73b59600-e130-484b-a156-045a42215a52
                          stations:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: Waterloo Station
                                categories:
                                  type: array
                                  example:
                                    - train_station
                                    - subway_station
                                total_ratings:
                                  type: integer
                                  example: 2248
                                place_id:
                                  type: string
                                  example: 73b59600-e130-484b-a156-045a42215a52
                          restaurants:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: Oxo Tower Restaurant
                                categories:
                                  type: array
                                  example:
                                    - bar
                                    - restaurant
                                    - food
                                total_ratings:
                                  type: integer
                                  example: 2248
                                place_id:
                                  type: string
                                  example: 73b59600-e130-484b-a156-045a42215a52

        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Unauthtorized
                    example: Nil JSON web token
        '400':
          content:
            application/json:
              schema:
                type: string
                items: message
                example:
                  - message: search_text is required field and should be less than 100 characters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                search_text:
                  type: string
                  description: Search Location
                  example: London
                attraction_radius:
                  type: integer
                  description: Radius in KM
                  example: 5
              required:
              - search_text
        description: Searches the target area for tourist attractions, stations, and restaurants. Descriptions can be generated by passing selected attraction ids to the area descriptions endpoint. Radius values are 2, 5 and 25 (km).
  "/api/v1/area/descriptions":
    post:
      summary: Area Descriptions
      tags:
      - Area Descriptions
      security:
        - bearerAuth: []
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Successfully Generated Area Descriptions
                  data:
                    type: object
                    properties:
                      result:
                        type: array
                        items: 
                        type: string
                        example: If you're looking for a neighbourhood that's brimming with history and culture, then look no further than London! Home to some of the world's most iconic landmarks including Big Ben, The National Gallery and Westminster Abbey, there's something for everyone to enjoy in this vibrant city. And when the sun goes down, the fun doesn't stop – London comes alive at night, so be sure to check out the city's many bars and restaurants for a truly unforgettable evening.
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Unauthtorized
                    example: Nil JSON web token
        '400':
          content:
            application/json:
              schema:
                type: string
                items: message
                example:
                  - message: Search Location does not exist
                  - message: Selected IDs cant be nil. Please insert at least 3 place_ids for the best description
                  - message: Invalid detail_text format. Kindly use the following format, ['famous for nightlife', 'Great location for exploring the city']
                  - message: detail_text cannot be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                search_location_id:
                  type: string
                  description: Search Location ID
                  example: 73b59600-e130-484b-a156-045a42215a12
                selected_ids:
                  type: array
                  example:
                    - 0d2b9014-a189-43ad-9b6a-0da0f322b328
                    - 03be2ca8-b894-49c3-a672-fab522133df9
                    - 09f96c35-18dd-4dc5-b557-0278a3d1f851
                detail_text:
                  type: array
                  items:
                  type: string
                  example: Famous for nightlife
              required:
              - search_location_id
              - selected_ids
              - detail_text
        description: Generates area descriptions from attraction ids and additional points of detail. Attraction ids are returned by the search_location endpoint. For best results, at least 3 attraction ids should be selected.
servers:
- url: https://app.listify.ai
  variables:
    defaultHost:
      default: app.listify.ai
